try {
    console.log('hello");
    
}
catch (err) {
    console.log(err.name);
    
}
